[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
name = "update"
version = "0.1.0"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
regex = "1.3.1"
reqwest = "0.9.21"
serde = "1.0.101"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.41"
