[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
name = "update"
version = "0.1.0"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"
regex = "1.1.0"
reqwest = "0.9.5"
serde = "1.0.81"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.33"
