[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
name = "update"
version = "0.1.0"

[dependencies]
clap = "2.30.0"
failure = "0.1.1"
regex = "0.2.6"
reqwest = "0.8.5"
serde = "1.0.27"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.9"
